### ISSUE TITLE
Getting error while running make model

### ISSUE THREAD

**Issue by rremani** [mathDR/reading-text-in-the-wild#5]
Getting attribute error, I followed all the steps but could not make the model, Please look into it.

(keras)ce@com19:~/Documents/reading-text-in-the-wild/DICT2$ python make_keras_dictnet_model.py 
Using Theano backend.
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, CuDNN 5105)
/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your CuDNN version is more recent then Theano. If you see problems, try updating Theano or downgrading CuDNN to version 4.
  warnings.warn(warn)
Traceback (most recent call last):
  File "make_keras_dictnet_model.py", line 87, in <module>
    model.compile(loss='categorical_crossentropy', optimizer=sgd)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/models.py", line 507, in compile
    self.y_train = self.get_output(train=True)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/containers.py", line 130, in get_output
    return self.layers[-1].get_output(train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 1030, in get_output
    X = self.get_input(train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 241, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 703, in get_output
    X = self.get_input(train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 241, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 1030, in get_output
    X = self.get_input(train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 241, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 703, in get_output
    X = self.get_input(train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 241, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 1030, in get_output
    X = self.get_input(train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 241, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 900, in get_output
    X = self.get_input(train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 241, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 310, in get_output
    X = self.get_input(train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 241, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 683, in get_output
    X = self.get_input(train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 241, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/ce/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 1225, in get_output
    return K.custom_spatial_2d_padding(X, padding=self.padding,
AttributeError: 'module' object has no attribute 'custom_spatial_2d_padding'

**Comment by mathDR** [comment]
Did you close this issue because you fixed it?

**Comment by rremani** [comment]
Ya, I fixed it. It was installation problem as my theano_backend.py was in layers folder but the code was importing from backend folder where it could not find that file. After installing again it worked.
