### ISSUE TITLE
Bugs when running make_keras_charnet_model.py

### ISSUE THREAD

**Issue by zhengdixin** [mathDR/reading-text-in-the-wild#9]
Hi, I come across a bug when running make_keras_charnet_model.py.

Using Theano backend.
Traceback (most recent call last):
  File "/home/zdx/reading-text-in-the-wild/CHAR2/make_keras_charnet_model.py", line 44, in <module>
    input_shape=(1, img_rows, img_cols),activation='relu',border_mode='same'))
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/models.py", line 299, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/engine/topology.py", line 397, in create_input_layer
    dtype=input_dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/engine/topology.py", line 1198, in Input
    input_tensor=tensor)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/engine/topology.py", line 1116, in __init__
    name=self.name)
TypeError: placeholder() got an unexpected keyword argument 'sparse'

I have make a breakpoint for the detailed value in __init__ . The sparse = false, name = 'concolutionId_input_1'. I don't know how to fix this bug. Would like to give me some advices?

Best wishes,
dixin Zheng

**Comment by mathDR** [comment]
Hi @zhengdixin The first thing I would try is installing Keras 0.3.3.  Your stacktrace shows you using Keras 1.2.0.  The code was never used with such a late version, so that would be the logical place to start.

**Comment by zhengdixin** [comment]
Hi, @mathDR , lots of help for your help. I installed Keras 0.3.3 with the link on your github and fixed this bug. Thanks again~
